//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Контакты</summary>
	[PublishedContentModel("contacts_Page")]
	public partial class Contacts_Page : PublishedContentModel, INavigatable, ISeoBase, ISitemapBase, IUrlNavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contacts_Page";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Contacts_Page(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contacts_Page, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Адрес: Юридический адрес
		///</summary>
		[ImplementPropertyType("addresss")]
		public string Addresss
		{
			get { return this.GetPropertyValue<string>("addresss"); }
		}

		///<summary>
		/// Електронная почта
		///</summary>
		[ImplementPropertyType("email_1")]
		public string Email_1
		{
			get { return this.GetPropertyValue<string>("email_1"); }
		}

		///<summary>
		/// Контакты: Заголовок области контактов
		///</summary>
		[ImplementPropertyType("label_Contacts")]
		public string Label_Contacts
		{
			get { return this.GetPropertyValue<string>("label_Contacts"); }
		}

		///<summary>
		/// Режим работы: Заголовок области режима работы
		///</summary>
		[ImplementPropertyType("label_OpertingMode")]
		public string Label_OpertingMode
		{
			get { return this.GetPropertyValue<string>("label_OpertingMode"); }
		}

		///<summary>
		/// Номер телефона (1)
		///</summary>
		[ImplementPropertyType("phoneNumber_1")]
		public string PhoneNumber_1
		{
			get { return this.GetPropertyValue<string>("phoneNumber_1"); }
		}

		///<summary>
		/// Номер телефона (2)
		///</summary>
		[ImplementPropertyType("phoneNumber_2")]
		public string PhoneNumber_2
		{
			get { return this.GetPropertyValue<string>("phoneNumber_2"); }
		}

		///<summary>
		/// Социальные сети
		///</summary>
		[ImplementPropertyType("socialNetworks")]
		public IEnumerable<IPublishedContent> SocialNetworks
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("socialNetworks"); }
		}

		///<summary>
		/// Текст режима работы: Текст описания режима работы
		///</summary>
		[ImplementPropertyType("text_OperatingMode")]
		public string Text_OperatingMode
		{
			get { return this.GetPropertyValue<string>("text_OperatingMode"); }
		}

		///<summary>
		/// Навигационный заголовок: Заголовок для навигационных элементов
		///</summary>
		[ImplementPropertyType("naviTitle")]
		public string NaviTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Navigatable.GetNaviTitle(this); }
		}

		///<summary>
		/// Убрать из навигации: Не показывать ссылку в навигационных элементах
		///</summary>
		[ImplementPropertyType("umbracoNavihide")]
		public bool UmbracoNavihide
		{
			get { return Umbraco.Web.PublishedContentModels.Navigatable.GetUmbracoNavihide(this); }
		}

		///<summary>
		/// Meta Description: Описание для поисковиков.  До 155 символов желательно.
		///</summary>
		[ImplementPropertyType("seoMetaDescription")]
		public string SeoMetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SeoBase.GetSeoMetaDescription(this); }
		}

		///<summary>
		/// No follow: Запретить поисковым роботам переходить по ссылкам на странице
		///</summary>
		[ImplementPropertyType("seoNoFollow")]
		public bool SeoNoFollow
		{
			get { return Umbraco.Web.PublishedContentModels.SeoBase.GetSeoNoFollow(this); }
		}

		///<summary>
		/// No index: Запретить индексацию страницы поисковым роботам
		///</summary>
		[ImplementPropertyType("seoNoIndex")]
		public bool SeoNoIndex
		{
			get { return Umbraco.Web.PublishedContentModels.SeoBase.GetSeoNoIndex(this); }
		}

		///<summary>
		/// Title: Заголовок во вкладке браузера и сниппете поисковиков
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SeoBase.GetSeoTitle(this); }
		}

		///<summary>
		/// Убрать из Sitemap: Не выводить страницу в sitemap.xml
		///</summary>
		[ImplementPropertyType("excludeFromSitemap")]
		public bool ExcludeFromSitemap
		{
			get { return Umbraco.Web.PublishedContentModels.SitemapBase.GetExcludeFromSitemap(this); }
		}

		///<summary>
		/// Альтернативный URL: Переопределить относительную ссылку на страницу
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return Umbraco.Web.PublishedContentModels.UrlNavigation.GetUmbracoUrlName(this); }
		}
	}
}
