//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1080 with alias "keywordsBase"
	/// <summary>Keywords Base</summary>
	public partial interface IKeywordsBase : IPublishedContent
	{
		/// <summary>Meta Keywords</summary>
		string SeoKeywords { get; }
	}

	/// <summary>Keywords Base</summary>
	[PublishedContentModel("keywordsBase")]
	public partial class KeywordsBase : PublishedContentModel, IKeywordsBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "keywordsBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KeywordsBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KeywordsBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Keywords: [Устарело] Ключевые слова для поисковиков
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return GetSeoKeywords(this); }
		}

		/// <summary>Static getter for Meta Keywords</summary>
		public static string GetSeoKeywords(IKeywordsBase that) { return that.GetPropertyValue<string>("seoKeywords"); }
	}
}
