//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>MadeRepair</summary>
	[PublishedContentModel("madeRepair")]
	public partial class MadeRepair : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "madeRepair";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MadeRepair(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MadeRepair, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Заголовок к пояснительному тексту
		///</summary>
		[ImplementPropertyType("captionToPicture")]
		public IHtmlString CaptionToPicture
		{
			get { return this.GetPropertyValue<IHtmlString>("captionToPicture"); }
		}

		///<summary>
		/// Картинка выполненного ремонта
		///</summary>
		[ImplementPropertyType("picture")]
		public IPublishedContent Picture
		{
			get { return this.GetPropertyValue<IPublishedContent>("picture"); }
		}

		///<summary>
		/// Расценка
		///</summary>
		[ImplementPropertyType("rate")]
		public string Rate
		{
			get { return this.GetPropertyValue<string>("rate"); }
		}

		///<summary>
		/// Площадь
		///</summary>
		[ImplementPropertyType("square")]
		public string Square
		{
			get { return this.GetPropertyValue<string>("square"); }
		}

		///<summary>
		/// Срок
		///</summary>
		[ImplementPropertyType("term")]
		public string Term
		{
			get { return this.GetPropertyValue<string>("term"); }
		}

		///<summary>
		/// Пояснительный текст
		///</summary>
		[ImplementPropertyType("textToPicture")]
		public string TextToPicture
		{
			get { return this.GetPropertyValue<string>("textToPicture"); }
		}
	}
}
