//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1077 with alias "overviewed"
	/// <summary>Overviewed</summary>
	public partial interface IOverviewed : IPublishedContent
	{
		/// <summary>Количество элементов</summary>
		int ItemsCount { get; }
	}

	/// <summary>Overviewed</summary>
	[PublishedContentModel("overviewed")]
	public partial class Overviewed : PublishedContentModel, IOverviewed
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "overviewed";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Overviewed(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Overviewed, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Количество элементов: Количество элементов списка на странице
		///</summary>
		[ImplementPropertyType("itemsCount")]
		public int ItemsCount
		{
			get { return GetItemsCount(this); }
		}

		/// <summary>Static getter for Количество элементов</summary>
		public static int GetItemsCount(IOverviewed that) { return that.GetPropertyValue<int>("itemsCount"); }
	}
}
