//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 5156 with alias "person"
	/// <summary>Person</summary>
	public partial interface IPerson : IPublishedContent
	{
		/// <summary>FirstName</summary>
		string FirstName { get; }

		/// <summary>LastName</summary>
		string LastName { get; }
	}

	/// <summary>Person</summary>
	[PublishedContentModel("person")]
	public partial class Person : PublishedContentModel, IPerson
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "person";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Person(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Person, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// FirstName
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return GetFirstName(this); }
		}

		/// <summary>Static getter for FirstName</summary>
		public static string GetFirstName(IPerson that) { return that.GetPropertyValue<string>("firstName"); }

		///<summary>
		/// LastName
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return GetLastName(this); }
		}

		/// <summary>Static getter for LastName</summary>
		public static string GetLastName(IPerson that) { return that.GetPropertyValue<string>("lastName"); }
	}
}
