//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Robots</summary>
	[PublishedContentModel("robots")]
	public partial class Robots : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "robots";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Robots(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Robots, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Запретить индексацию: Запрет индексации всех страниц сайта
		///</summary>
		[ImplementPropertyType("isDisallowed")]
		public bool IsDisallowed
		{
			get { return this.GetPropertyValue<bool>("isDisallowed"); }
		}

		///<summary>
		/// Ручное заполнение: Заполнить robots.txt вручную
		///</summary>
		[ImplementPropertyType("isManual")]
		public bool IsManual
		{
			get { return this.GetPropertyValue<bool>("isManual"); }
		}

		///<summary>
		/// Содержимое: Содержимое robots.txt заполненное вручную
		///</summary>
		[ImplementPropertyType("robotsContent")]
		public string RobotsContent
		{
			get { return this.GetPropertyValue<string>("robotsContent"); }
		}
	}
}
