//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1083 with alias "sitemapBase"
	/// <summary>Sitemap Base</summary>
	public partial interface ISitemapBase : IPublishedContent
	{
		/// <summary>Убрать из Sitemap</summary>
		bool ExcludeFromSitemap { get; }
	}

	/// <summary>Sitemap Base</summary>
	[PublishedContentModel("sitemapBase")]
	public partial class SitemapBase : PublishedContentModel, ISitemapBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sitemapBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SitemapBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SitemapBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Убрать из Sitemap: Не выводить страницу в sitemap.xml
		///</summary>
		[ImplementPropertyType("excludeFromSitemap")]
		public bool ExcludeFromSitemap
		{
			get { return GetExcludeFromSitemap(this); }
		}

		/// <summary>Static getter for Убрать из Sitemap</summary>
		public static bool GetExcludeFromSitemap(ISitemapBase that) { return that.GetPropertyValue<bool>("excludeFromSitemap"); }
	}
}
