//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Вид ремонта</summary>
	[PublishedContentModel("typeRepair")]
	public partial class TypeRepair : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "typeRepair";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TypeRepair(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TypeRepair, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Название типа ремонта
		///</summary>
		[ImplementPropertyType("caption")]
		public string Caption
		{
			get { return this.GetPropertyValue<string>("caption"); }
		}

		///<summary>
		/// Список ремонтных работ вида ремонта
		///</summary>
		[ImplementPropertyType("listOfRepairWorks")]
		public IEnumerable<string> ListOfRepairWorks
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("listOfRepairWorks"); }
		}

		///<summary>
		/// Картинка вида ремонта
		///</summary>
		[ImplementPropertyType("pictureTypeRepar")]
		public IPublishedContent PictureTypeRepar
		{
			get { return this.GetPropertyValue<IPublishedContent>("pictureTypeRepar"); }
		}

		///<summary>
		/// Price up to
		///</summary>
		[ImplementPropertyType("priceUpTo")]
		public IHtmlString PriceUpTo
		{
			get { return this.GetPropertyValue<IHtmlString>("priceUpTo"); }
		}

		///<summary>
		/// Описание типа ремонта
		///</summary>
		[ImplementPropertyType("repairTypeDescription")]
		public string RepairTypeDescription
		{
			get { return this.GetPropertyValue<string>("repairTypeDescription"); }
		}

		///<summary>
		/// Текст к картинке
		///</summary>
		[ImplementPropertyType("textToPicture")]
		public string TextToPicture
		{
			get { return this.GetPropertyValue<string>("textToPicture"); }
		}
	}
}
