//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Настройки</summary>
	[PublishedContentModel("websiteSettings")]
	public partial class WebsiteSettings : PublishedContentModel, IScriptsSettings
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "websiteSettings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public WebsiteSettings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WebsiteSettings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body - после открытия: После открывающего тега body
		///</summary>
		[ImplementPropertyType("bodyAfterOpening")]
		public string BodyAfterOpening
		{
			get { return Umbraco.Web.PublishedContentModels.ScriptsSettings.GetBodyAfterOpening(this); }
		}

		///<summary>
		/// Body - перед закрытием: Перед закрывающим тегом body
		///</summary>
		[ImplementPropertyType("bodyBeforeClosing")]
		public string BodyBeforeClosing
		{
			get { return Umbraco.Web.PublishedContentModels.ScriptsSettings.GetBodyBeforeClosing(this); }
		}

		///<summary>
		/// Head - после открытия: После открывающего тега head
		///</summary>
		[ImplementPropertyType("headAfterOpening")]
		public string HeadAfterOpening
		{
			get { return Umbraco.Web.PublishedContentModels.ScriptsSettings.GetHeadAfterOpening(this); }
		}

		///<summary>
		/// Head - перед закрытием: Перед закрывающим тегом head
		///</summary>
		[ImplementPropertyType("headBeforeClosing")]
		public string HeadBeforeClosing
		{
			get { return Umbraco.Web.PublishedContentModels.ScriptsSettings.GetHeadBeforeClosing(this); }
		}
	}
}
